### ISSUE TITLE
All logs should be JSON

### ISSUE THREAD

**Issue by phutchins** [Storj/complex#12]
When parsing logs from the renter, we process them as JSON as nearly all of the logs are formatted that way. When we run across a non JSON formatted log entry, it errors in our log processing and is not parsed properly which makes it difficult to gather data on the logs.

For instance, in a 24 hour period I found 72 million instances of "DEPRECATED: The method RenterInterface#acceptOffer is deprecated and will be removed in storj-lib@5.0.0". The log level on this should probably be changed so that it isn't logged at log level 2 and it should also be JSON.

**Comment by 161chihuahuas** [comment]
There is no log level set here. This is separate from all other logging and is to warn the implementor to update their code. It should not be suppressed at any log level. 

Can the log processor not just simply ignore these?

**Comment by 161chihuahuas** [comment]
(Also this is coming from `storj-lib`)
