### ISSUE TITLE
Add documentation for generating keys

### ISSUE THREAD

**Issue by utdrmac** [Storj/complex#41]
Probably shouldn't be using the example key.

**Comment by braydonf** [comment]
```js
// require necessary libs, get entropy, and create a key
var HDKey = require('hdkey');
var seed = require('crypto').randomBytes(64);
var hdkey = HDKey.fromMasterSeed(seed);

// to keep for other future uses
console.log(hdkey.privateExtendedKey);

// deriving the key for complex use (detailed in sip32)
var complexKey = hdkey.derive("m/3000'/0'");

// this will output expected private key used in configs
console.log(complexKey.privateExtendedKey);

// for this config value in complex
let options = {};
options.networkPrivateExtendedKey = complexKey.privateExtendedKey;

// this is the key used in contracts and contacts
console.log(complexKey.publicExtendedKey);
```

For more info: 
- https://github.com/Storj/sips/blob/master/sip-0032.md
- https://github.com/cryptocoinjs/hdkey/blob/master/lib/hdkey.js

Edit: Updated code to be able to be copy/pastable.

**Comment by super3** [comment]
@braydonf Can you add this as a page in the documentation?

**Comment by utdrmac** [comment]
Maybe also mention how the networkIndex number works too?

Side note, in your example above, if you just copy/paste that and run it, you get "'options' not found" type error.

**Comment by 161chihuahuas** [comment]
The example above is also performed for you if you use `storj-lib`: https://storj.github.io/core/module-storj_utils.html#-static-createComplexKeyFromSeed__anchor

```js
const {randomBytes} = require('crypto');
const {createComplexKeyFromSeed} = require('storj-lib').utils;
const complexKey = createComplexKeyFromSeed(randomBytes(64));
```

**Comment by braydonf** [comment]
I forgot about that method.

**Comment by braydonf** [comment]
Added to readme
