### ISSUE TITLE
Port 4000 is forwarded yet still says unreachable

### ISSUE THREAD

**Issue by utdrmac** [Storj/complex#42]
`{"level":"warn","message":"you are not publicly reachable, trying traversal strategies...","timestamp":"2016-12-30T04:49:45.885Z"}`

Running on an EC2 node. Have public IP. Have port 4000 allowed in security group.

Dummy testing for basic connectivity:

```
[drmac@othala ~]$ telnet 51.111.10.130 4000
Trying 51.111.10.130...
Connected to ec2-51-111-10-130.compute-1.amazonaws.com.
Escape character is '^]'.
GET /

HTTP/1.1 405 Method Not Allowed
Allow: POST
Content-Type: application/json
Content-Length: 63
Date: Fri, 30 Dec 2016 04:53:18 GMT
Connection: close

{"code":"MethodNotAllowedError","message":"GET is not allowed"}Connection closed by foreign host.
```

What other ports need to be opened/forwarded?

**Comment by braydonf** [comment]
It may be helpful to take a look at https://github.com/Storj/integration for general idea of all of the pieces, and higher level view.

**Comment by utdrmac** [comment]
Unfortunately, reading through everything on `integration` didn't really help. `complex` appears to be just middleware between RabbitMQ/Mongo and `bridge` via an RPC API.

Based on reading whitepaper v2, which doesn't mention `complex` at all, `bridge` is responsible for connecting to the network, handling contracts, facilitating regular audits, ensuring enough MIRROR copies, etc.

Why does my `complex` need to be publicly addressable if only my `bridge` (or multiple `bridge`s inside my private network) is talking to it?

**Comment by braydonf** [comment]
The renter's need to be publicly addressable (as they are part of the Storj network), the landlord does not, since it's queuing up work to the renters.

**Comment by braydonf** [comment]
If you haven't already, please join community.storj.io, there is a bridge channel which should cover complex and such.
