### ISSUE TITLE
Bridge can't restart if seeds goes down

### ISSUE THREAD

**Issue by retrohacker** [Storj/complex#43]
The Bridge caches it's know list of good seeds in mongo. When the application starts, it bootstraps itself into the kad overlay with both the list of seeds provided through the configuration file and the list of known good seeds in Mongo.

https://github.com/Storj/complex/blob/master/lib/renter.js#L130

```js
this.network = storj.Renter({
...
  seedList: this._opts.networkOpts.seedList.concat(seeds),
...
});
```

If the config specifies an empty `seedList`, the renter will startup just fine and wait to be contacted by a farmer to bootstrap the network. Once a farmer contacts it, this contact will be added to Mongo. If the farmer and bridge go offline at approximately the same time, and the bridge restarts, the bridge will attempt to reenter the network through the offline farmer and fail.

https://github.com/Storj/core/blob/master/lib/network/index.js#L265-L284

```js
    async.detectSeries(self._options.seedList, function(uri, next) {
      self._logger.info('attempting to join network via %s', uri);
      self.connect(uri, function(err) {
        if (err) {
          self._logger.warn('failed to connect to seed %s', uri);
          next(null, false);
        } else {
          self._logger.info('connected to the storj network via %s', uri);
          next(null, true);
        }
      });
    }, function(err, result) {
      if (err || !result) {
        return onConnected(new Error('Failed to join the network'));
      }

      // NB: Force re-entry into network to refresh routes every 10 minutes
      setTimeout(_trySeeds, constants.NET_REENTRY);
      onConnected(null);
    });
```

If an empty `seedList` is a valid state, then shouldn't a stale mongo client cache be a valid state?

This becomes a problem when testing locally, when I tear down the whole cluster and stand it back up, the renter/farmer don't always pull the same ip address as before but Mongo keeps the old address cached. This results in strange behaviour (i.e. I've seen the renter trying to enter the network through RabbitMQ).

**Comment by retrohacker** [comment]
For now, I'm floating a patch for local development that keeps the renter from loading in seeds from Mongo.

**Comment by braydonf** [comment]
For development purposes, the way I have it working is for the farmers to contact the renters, haven't had any issues there.

**Comment by braydonf** [comment]
Though, there were not any issues when just leaving all the seedList empty.

**Comment by braydonf** [comment]
If there is a patch, please send to relevant repo, otherwise closing as outdated.
