### ISSUE TITLE
Bridge contact list not updated

### ISSUE THREAD

**Issue by littleskunk** [Storj/complex#54]
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

```
GUI 5.0.0
Daemon 2.5.2
Core 6.4.2
Protocol 1.1.0
```
```
info	
title	"Storj Bridge"
version	"5.14.0"
description	"Access the Storj network using a simple REST API."
x-protocol-version	"1.1.0"
x-core-version	"6.4.2"
```

Replace the values below using the output from `node --version`.

```
v6.10.2
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

Farmer was connected with a tunnel connection. He fixed that problem and is now using UPnP. Farmer is online for more than one hour now. Port check shows an open port. Logfile shows communication with the bridge.

A few examples:
```
{"level":"warn","message":"you are not publicly reachable, trying traversal strategies...","timestamp":"2017-05-03T09:36:43.500Z"}
{"level":"info","message":"successfully traversed NAT via UPnP: 195.211.136.9:28268","timestamp":"2017-05-03T09:36:43.584Z"}
{"level":"info","message":"node bound and port mapped: 28268","timestamp":"2017-05-03T09:36:43.584Z"}
{"level":"info","message":"node created with nodeID 967e01f547a466bc1fb3d4f3ecb82f5548c7a0bf","timestamp":"2017-05-03T09:36:43.589Z"}
{"level":"info","message":"clock is synchronized with ntp, delta: 296 ms","timestamp":"2017-05-03T09:36:43.606Z"}
[...]
{"level":"info","message":"sending FIND_NODE message to {\"userAgent\":\"6.4.1\",\"protocol\":\"1.1.0\",\"hdKey\":\"xpub6AHweYHAxk1EhJSBctQD1nLWPog6Sy2eTpKQLExR1hfzTyyZQWvU4EYNXv1NJN7GpLYXnDLt4PzN874g6zSjAQdFCHZN7U7nbYKYVDUzD42\",\"hdIndex\":13316789,\"address\":\"104.196.51.2\",\"port\":8472,\"nodeID\":\"8e102ca4b55f1ff6e26dd9db2f65f45e39ee7043\",\"lastSeen\":1493803834217}","timestamp":"2017-05-03T09:37:13.547Z"}
{"level":"info","message":"received valid message from {\"userAgent\":\"6.4.1\",\"protocol\":\"1.1.0\",\"hdKey\":\"xpub6AHweYHAxk1EhJSBctQD1nLWPog6Sy2eTpKQLExR1hfzTyyZQWvU4EYNXv1NJN7GpLYXnDLt4PzN874g6zSjAQdFCHZN7U7nbYKYVDUzD42\",\"hdIndex\":13316789,\"address\":\"104.196.51.2\",\"port\":8472,\"nodeID\":\"8e102ca4b55f1ff6e26dd9db2f65f45e39ee7043\",\"lastSeen\":1493575472129}","timestamp":"2017-05-03T09:37:14.349Z"}
[...]
{"level":"info","message":"sending OFFER message to {\"userAgent\":\"6.4.1\",\"protocol\":\"1.1.0\",\"hdKey\":\"xpub6AHweYHAxk1EhJSBctQD1nLWPog6Sy2eTpKQLExR1hfzTyyZQWvU4EYNXv1NJN7GpLYXnDLt4PzN874g6zSjAQdFCHZN7U7nbYKYVDUzD42\",\"hdIndex\":14338782,\"address\":\"104.196.137.222\",\"port\":8470,\"nodeID\":\"9789965a1bd33f1f1d618d66ffb61b00bde0aad7\",\"lastSeen\":1493804234897}","timestamp":"2017-05-03T09:45:10.134Z"}
{"level":"info","message":"received valid message from {\"userAgent\":\"6.4.1\",\"protocol\":\"1.1.0\",\"hdKey\":\"xpub6AHweYHAxk1EhJSBctQD1nLWPog6Sy2eTpKQLExR1hfzTyyZQWvU4EYNXv1NJN7GpLYXnDLt4PzN874g6zSjAQdFCHZN7U7nbYKYVDUzD42\",\"hdIndex\":14338782,\"address\":\"104.196.137.222\",\"port\":8470,\"nodeID\":\"9789965a1bd33f1f1d618d66ffb61b00bde0aad7\",\"lastSeen\":1493439486145}","timestamp":"2017-05-03T09:45:10.548Z"}
```

Bridge should notice him as online farmer and list his new IP and port.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

The bridge doesn't update the information. He is listed as offline farmer.
```
lastSeen	"2017-05-03T07:39:42.547Z"
port	15084
address	"client021.storj.dk"
userAgent	"6.3.2"
protocol	"1.1.0"
lastTimeout	"2017-05-03T09:45:02.615Z"
responseTime	15946.088361004064
timeoutRate	0.04352332175925926
nodeID	"967e01f547a466bc1fb3d4f3ecb82f5548c7a0bf"
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Setup new farmer and use a tunnel connect
2. Restart farmer with UPnP or public IP
3. Take a look at api.storj.io/contacts

**Comment by littleskunk** [comment]
As far as I can see my own farmer contact information are only updated on responseTime change. Looks like this line of code: https://github.com/Storj/complex/blob/8a5f8f7a2389f2828ea6c9c2041ee1e4471e9466/lib/landlord.js#L249

@bookchin mentioned that this should update as well: https://github.com/Storj/complex/blob/8a5f8f7a2389f2828ea6c9c2041ee1e4471e9466/lib/renter.js#L300

**Comment by 161chihuahuas** [comment]
That event calls `Contact#record` which is here: https://github.com/Storj/service-storage-models/blob/master/lib/models/contact.js#L72-L88

That method looks correct to me, though, and it also has not been changed in some time.

**Comment by littleskunk** [comment]
It was never working but we (support team) told the farmer they have to wait a few hours for an update of the contact list.

**Comment by littleskunk** [comment]
I found out that not all bridge renter are updating the contact list. I have to send at least one PING to each bridge renter to be sure one of them will update the contact list.

Steps to reproduce it:
1.) Send one ping to each renter.
2.) Query the contact list to see if the contact information gets updated.
3.) Create a list of positive and negative calls. Maybe repeat the game a few times to see if it is random or if there is any pattern.

Simple ping like this one:
```
var keypair = storj.KeyPair(node.privatekey);
	var id = hat.rack(160)();
	var nonce = Date.now();
	var data = {
		method: 'PING',
		params: {
			contact: {
				address: node.address,
				port: node.port,
				nodeID: keypair.getNodeID(),
				protocol: '1.1.0',
				userAgent: '6.8.0'
			},
			nonce: nonce,
			signature: keypair.sign(id + nonce),
		},
		id: id,
	};
	
	request.post({
		url: node.url,
		json: data,
		timeout: 30000
	}, (err, res, data) => {
		if (err) {
			console.log('Error request:', err);
		} else if (res.statusCode !== 200) {
			console.log('Status:', res.statusCode);
		} else {
			console.log(data);
		}
		process.nextTick(callback);
	});
```

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
