### ISSUE TITLE
Example multi config is missing landlord MongoDB url

### ISSUE THREAD

**Issue by abrkn** [Storj/complex#72]
```
ubuntu@ip-172-31-31-81:~/complex$ bin/storj-complex.js -c example/multi-config.json
assert.js:81
  throw new assert.AssertionError({
  ^
AssertionError: Invalid mongoUrl
    at new LandlordConfig (/home/ubuntu/complex/lib/config.js:102:3)
```

**Comment by rriemann** [comment]
The medium article is trending that mentions this issue and no reaction for two weeks. 🏖️

https://shitcoin.com/storj-not-a-dropbox-killer-1a9f27983d70

**Comment by braydonf** [comment]
Example has been updated.

 However, please see example setups from these:
- https://github.com/storj/integration
- https://github.com/storj/storj-sdk

There are far too many pieces to connect, as is current, for these individual examples to be of much help. 

Furthermore there is work already in progress, implementing SIP6, to simplify a lot of the architecture to make setup much more smooth for bridge and related. Please see:
- https://github.com/Storj/sips/blob/master/sip-0006.md
- https://github.com/Storj/sips/pull/20
- https://github.com/Storj/sips/pull/34

**Comment by rriemann** [comment]
> Furthermore there is work already in progress, implementing SIP6, to simplify a lot of the architecture to make setup much more smooth for bridge and related. 

The developers of Discourse decided to tackle this problem by providing a Docker-based installation routine: https://github.com/discourse/discourse_docker
