### ISSUE TITLE
First responder for ALLOC messages

### ISSUE THREAD

**Issue by braydonf** [Storj/complex#83]
Currently the first responder for the ALLOC message in `_publishContract` will be returned to the client for uploading. This could lead towards the fastest repondes receiving most of the initial uploaded data, so it may be worth while to consider somewhat randomizing which response is returned to the client for the initial upload.

Relevant code is at https://github.com/Storj/complex/blob/master/lib/renter.js#L585

**Comment by braydonf** [comment]
A couple of ideas:

1) Send out contracts in groups of 6 or 3, with randomized ordering, with small delays between
2) Keep track of the first responders, and make sure that second, third and fourth get their chance
3) Wait a second to gather responses, and then randomly select one

**Comment by littleskunk** [comment]
1.) The old contract PUBLISH was working this way. 3 farmer are getting the message and will relay it with a small delay. Not a perfect solution but better than the current situation.

2.) I would use that rule against you. On smaller shards I will delay my response. The bridge will make sure that I win only the big shards.

3.) Perfect solution but we need a bit more than 1 sec. A pi3 farmer in singapur would need 1.4 sec.
Log example from a slow Odroids similar to a pi3. They need 1 sec for the client side validations.
```
{"level":"info","message":"received valid message from {\"userAgent\":\"6.6.0\",\"protocol\":\"1.1.0\",\"address\":\"104.233.106.150\",\"port\":4000,\"nodeID\":\"048e125f8374a9ac538711dc0ee89fca16743a08\",\"lastSeen\":1505089736189}","timestamp":"2017-10-01T00:03:14.128Z"}
{"level":"info","message":"sending PUBLISH message to {\"userAgent\":\"8.1.0\",\"protocol\":\"1.2.0\",\"address\":\"91.223.147.126\",\"port\":4004,\"nodeID\":\"0481b448acd08d48d1093327a3ded1197d01d0a5\",\"lastSeen\":1506816156784}","timestamp":"2017-10-01T00:03:14.137Z"}
{"level":"info","message":"sending PUBLISH message to {\"userAgent\":\"8.1.0\",\"protocol\":\"1.2.0\",\"address\":\"nobodyi.sytes.net\",\"port\":4000,\"nodeID\":\"04ef586fa6631f99b9d8da63282eea4861cbf52c\",\"lastSeen\":1506816031110}","timestamp":"2017-10-01T00:03:14.251Z"}
{"level":"info","message":"sending PUBLISH message to {\"userAgent\":\"8.1.0\",\"protocol\":\"1.2.0\",\"address\":\"217.145.198.244\",\"port\":4036,\"nodeID\":\"04e5a1e3f006dd044481f2d23e541d6544e73377\",\"lastSeen\":1506816116922}","timestamp":"2017-10-01T00:03:14.329Z"}
{"level":"info","message":"received valid message from {\"userAgent\":\"8.1.0\",\"protocol\":\"1.2.0\",\"address\":\"91.223.147.126\",\"port\":4004,\"nodeID\":\"0481b448acd08d48d1093327a3ded1197d01d0a5\",\"lastSeen\":1506804763806}","timestamp":"2017-10-01T00:03:14.745Z"}
{"level":"info","message":"received valid message from {\"userAgent\":\"8.1.0\",\"protocol\":\"1.2.0\",\"address\":\"217.145.198.244\",\"port\":4036,\"nodeID\":\"04e5a1e3f006dd044481f2d23e541d6544e73377\",\"lastSeen\":1506681941435}","timestamp":"2017-10-01T00:03:14.792Z"}
{"level":"info","message":"sending OFFER message to {\"userAgent\":\"7.0.3\",\"protocol\":\"1.2.0\",\"hdKey\":\"xpub6AHweYHAxk1EhJSBctQD1nLWPog6Sy2eTpKQLExR1hfzTyyZQWvU4EYNXv1NJN7GpLYXnDLt4PzN874g6zSjAQdFCHZN7U7nbYKYVDUzD42\",\"hdIndex\":188,\"address\":\"renter-187.renters.prod.storj.io\",\"port\":8400,\"nodeID\":\"065b56dcabbf341d384f07c4af60fae803c474a9\",\"lastSeen\":1505411590693}","timestamp":"2017-10-01T00:03:15.186Z"}
```

**Comment by braydonf** [comment]
I'd like to avoid introducing artificial delays where possible, as we're already dealing with timeout issues and do not need to increase those issues. We can try a few strategies and see what works best.

Perhaps there are some issues on the client that need to be solved to respond faster, so that there is less difference between hardware and geography.

**Comment by braydonf** [comment]
@littleskunk How long does approximateSize take? I think it's `storage._size` in the code.
