### ISSUE TITLE
let client choose storage nodes instead of the bridge

### ISSUE THREAD

**Issue by akostadinov** [Storj/complex#90]
When client chooses the nodes, then client will know their response time to/from the nodes. ATM assume bridge is located in Belgium but client is located in Germany. Then German nodes will have a better response time to client compared to Belgium nodes but Bridge will see better response times from Belgium nodes. That means nodes closer to bridges have better propositions than nodes away from bridges. But this is not fair to nodes as well could be suboptimal for the clients.
Additionally client can configure personal preferences about choosing nodes which would be hard to account in the bridges.
I'm very new to storj so excuse me if I misunderstood something.

**Comment by littleskunk** [comment]
This information is outdated. Responsetime is not used for shard distribution anymore.

**Comment by akostadinov** [comment]
Ok, this is what I read around today. You can close if it is not correct.

**Comment by braydonf** [comment]
Technically `responseTime` is still used, we're moving to use `reputation`, however there is a wait period so that there can be several responses: https://github.com/Storj/complex/blob/81a101cba61c860c7119b05627dc748d685d5f72/lib/renter.js#L600-L613 The wait period is configurable and is usually largrer than the ping time between two sides of Earth.

**Comment by akostadinov** [comment]
Looks like it is a factor but there is a random factor as well `Math.random() * responses.length` if I understand this correctly.

**Comment by braydonf** [comment]
Yes, random ends up being a pretty decent method to distribute load without introducing race conditions. We do the same for the initial farmer selection: https://github.com/Storj/bridge/blob/master/lib/server/routes/frames.js#L158-L185
